### PR TITLE
Fixed layout across all devices.

### PR DESCRIPTION
**Pull request by ploddingpawn**
### Ticket
[[Ticket Link](https://trello.com/c/DrULMhnN/65-fix-layout-for-all-devices)]

### What is changed / added
Fixed layout so that it doesn't look weird on tablet. 

### Screenshots
Mathematical
WHAT WE DO

### CODE REVIEW

**Review by lx1922 — COMMENTED** [review]
Just to confirm you have checked it on mobile and desktop as well right? Just so that there's no regression...

Thanks

**Comment by anthonytedja** [comment]
There are some overflowing and overlaying bugs on mobile screens

image image

**Comment by anthonytedja** [comment]
We should center the newsletter input and button on smaller screens

image

**Comment by anthonytedja** [comment]
This isn't as necessary but if we could move the CTA section button underneath executives and associates and then center those two on smaller screens to make it similar to the events button section that would be better 

image

**Comment by ploddingpawn** [comment]
I still can't seem to see the overlaying issue with the DH picture so I'm not sure what I can do about that. I did fix the overflowing issue, put the 'Join Us' button under 'executives' and 'associates' for mobile, and centered the newsletter input/button on smaller screens. I also double-checked tablet view after these fixes and it looks ok to me.  

image
WHAT WE DO
image


Let me know if there are any other issues!

**Review by lx1922 — APPROVED** [review]

**Pull request merged**
