### PR TITLE
Dev- Adding linting and type checks to pre-push and github actions

### PR DESCRIPTION
**Pull request by TheFatPanda97**
### Ticket
[Ticket Link](https://trello.com/c/CNmOveDA/13-dev-adding-linting-rule-to-github-actions-and-husky)

### What is changed / added
- added husky
- added pre-push check for linting and type checking
- added GitHub actions for linting and type checking

### CODE REVIEW

**Review by lx1922 — APPROVED** [review]
This definitely helps!

**Comment by nigow** [comment]
@TheFatPanda97 can you clean up the commits? I'm afraid it's hard to see what each commit does.

**Comment by AaronCGoidel** [comment]
> @TheFatPanda97 can you clean up the commits? I'm afraid it's hard to see what each commit does. 

I agree. I'd be happy squashing these when we merge, instead though.

**Comment by TheFatPanda97** [comment]
> > @TheFatPanda97 can you clean up the commits? I'm afraid it's hard to see what each commit does.
> 
> I agree. I'd be happy squashing these when we merge, instead though.

Yep, I think squash and merging would be good enough.

**Comment by TheFatPanda97** [comment]
[Dev - Adding linting rule to GitHub Actions and husky](https://trello.com/c/CNmOveDA/13-dev-adding-linting-rule-to-github-actions-and-husky)

**Comment by nigow** [comment]
It might boil down to personal taste, but I see each commit when I see a PR (because it might include unmerged commits from a different branch). So I would prefer PRs git squashed to smaller commits with good commit messages before review, but we didn't decide on this rule so we can always discuss later.

**Comment by TheFatPanda97** [comment]
> It might boil down to personal taste, but I see each commit when I see a PR (because it might include unmerged commits from a different branch). So I would prefer PRs git squashed to smaller commits with good commit messages before review, but we didn't decide on this rule so we can always discuss later.

Hmm I see, I think it's just a different type of review style. For me, I would just look at the final changes rather than the commit since there may be a lot of testing in the commits. Since we are doing a squashing and merging at the end, the master branch would only have 1 commit.

**Pull request merged**
